/* eslint-env node */
/* eslint-disable @typescript-eslint/no-var-requires */
/**
 * Custom Expo Config Plugin — withIosFixes
 *
 * AppDelegate.swift is auto-generated by Expo on every fresh `expo run:ios`.
 * This plugin re-applies two lines that would otherwise be lost:
 *
 *  1. import Firebase
 *  2. FirebaseApp.configure()
 */

const { withAppDelegate } = require('expo/config-plugins');

function addFirebaseToAppDelegate(contents) {
  if (contents.includes('FirebaseApp.configure()')) return contents; // already present

  // Add  import Firebase  after  import Expo
  contents = contents.replace(
    'import Expo',
    'import Expo\nimport Firebase'
  );

  // Add  FirebaseApp.configure()  as first line inside didFinishLaunchingWithOptions
  contents = contents.replace(
    'let delegate = ReactNativeDelegate()',
    'FirebaseApp.configure()\n    let delegate = ReactNativeDelegate()'
  );

  return contents;
}

module.exports = function withIosFixes(config) {
  return withAppDelegate(config, (c) => {
    c.modResults.contents = addFirebaseToAppDelegate(c.modResults.contents);
    return c;
  });
};
